require 'app'
require 'sinatra/activerecord/rake'
require 'fileutils'

namespace :db do
  task :environment do
    require 'rubygems'
    require 'logger'
    require 'active_record'
    ActiveRecord::Base.establish_connection :adapter => 'postgresql', :encoding => "utf8", 
      :username => "root", :password => "", :database => 'psl_development'
  end

  desc "Migrate the database"
  task(:migrate => :environment) do
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Migration.verbose = true
    ActiveRecord::Migrator.migrate("db/migrate")
  end
end

namespace :server do
  task :ping do
   sh %{  'Hello' }
    
  end

end